apiVersion: v1
kind: Service
metadata:
  annotations:
    generated.by: 8gwifi.org
  name: service.name.3
  namespace: default
spec:
  ports:
  - name: nameme_01
    port: 3000
    protocol: tcp
    targetPort: 3000
  selector:
    app: demo.54
  type: NodePort

#This is Pod Configuration Kube definition
---
kind: Pod
metadata:
  labels:
    app: demo.54
  namespace: default
spec:
  containers:
  - imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3000
      name: portname.0
      protocol: tcp
  terminationGracePeriodSeconds: 0

#Generating kubernetes YAML file for the Service backend.yml
#This is Service Configuration Kube definition
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    generated.by: 8gwifi.org
  name: service.name.5
  namespace: default
spec:
  ports:
  - name: nameme_01
    port: 3001
    protocol: tcp
    targetPort: 3001
  selector:
    app: demo.92
  type: NodePort

#This is Pod Configuration Kube definition
---
kind: Pod
metadata:
  labels:
    app: demo.92
  namespace: default
spec:
  containers:
  - imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3001
      name: portname.0
      protocol: tcp
  terminationGracePeriodSeconds: 0